# Generated by Django 5.1.3 on 2024-11-11 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=64)),
                ('rol', models.CharField(choices=[('Cliente', 'Cliente'), ('Estilista', 'Estilista'), ('Administrador', 'Administrador'), ('Recepcionista', 'Recepcionista')], max_length=13)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=64)),
                ('rol', models.CharField(choices=[('Cliente', 'Cliente'), ('Estilista', 'Estilista'), ('Administrador', 'Administrador'), ('Recepcionista', 'Recepcionista')], max_length=13)),
                ('historial_citas', models.JSONField(blank=True, default=list)),
                ('numero_cliente', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estilista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=64)),
                ('rol', models.CharField(choices=[('Cliente', 'Cliente'), ('Estilista', 'Estilista'), ('Administrador', 'Administrador'), ('Recepcionista', 'Recepcionista')], max_length=13)),
                ('agenda', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=64)),
                ('rol', models.CharField(choices=[('Cliente', 'Cliente'), ('Estilista', 'Estilista'), ('Administrador', 'Administrador'), ('Recepcionista', 'Recepcionista')], max_length=13)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('duracion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_citas', to='gestionApp.cliente')),
                ('estilista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_estilista', to='gestionApp.estilista')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita_servicios', to='gestionApp.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='CitaServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='gestionApp.cita')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita_servicio', to='gestionApp.servicio')),
            ],
        ),
    ]
